spark.master                      local[2]
spark.driver.memory               1g
spark.sql.shuffle.partitions      4
spark.sql.catalogImplementation   hive
spark.hadoop.hive.metastore.uris  thrift://metastore:9083
spark.sql.warehouse.dir           hdfs://namenode:8020/user/hive/warehouse
